### PR TITLE
feat: update dependencies and fix type errors

### PR DESCRIPTION
**Pull request by timrijkse**
Updated dependencies to React 18 and fixed type errors.

### CODE REVIEW

**Review by antoine10245 — APPROVED** [review]
It seems legit to me and highly needed. otherwise, it won't work with react 18 apps using ts

**Review by antoine10245 — APPROVED** [review]

**Comment by florentpergoud** [comment]
@CHEWCHEWW could you please merge this one ? 
It will be highly helpfull :)

**Comment by w0rldart** [comment]
@CHEWCHEWW anything in particular stopping from getting this reviewed and merged?

**Review by ebopwau — APPROVED** [review]

**Review by w0rldart — APPROVED** [review]

**Comment by joyceawt** [comment]
could this please be merged? @timrijkse @CHEWCHEWW

**Comment by CHEWCHEWW** [comment]
thank you for your commit!
but i'll reopen new pr and merge it.

**Pull request closed without merging**
